// max parts to display, for ex:
// the path: /user/something/desktop/project/a
// for 2, it should be shortened to: project/a
// to make it easier to navigate
export const maxProjectPathParts = 4;
// the file name where notes are stored - it behaves like a "language" in most cases
// but it has acceptations on the UI and exported files
export const notesFileName = '$__autogenerated_translator_notes';
